#include "cpu.h"

void CPU::opcode_00() { opcode_nop(); }
void CPU::opcode_01() {  }
void CPU::opcode_02() {}
void CPU::opcode_03() {}
void CPU::opcode_04() {}
void CPU::opcode_05() {}
void CPU::opcode_06() {}
void CPU::opcode_07() {}
void CPU::opcode_08() {}
void CPU::opcode_09() {}
void CPU::opcode_0a() {}
void CPU::opcode_0b() {}
void CPU::opcode_0c() {}
void CPU::opcode_0d() {}
void CPU::opcode_0e() {}
void CPU::opcode_0f() {}

void CPU::opcode_10() {}
void CPU::opcode_11() {}
void CPU::opcode_12() {}
void CPU::opcode_13() {}
void CPU::opcode_14() {}
void CPU::opcode_15() {}
void CPU::opcode_16() {}
void CPU::opcode_17() {}
void CPU::opcode_18() {}
void CPU::opcode_19() {}
void CPU::opcode_1a() {}
void CPU::opcode_1b() {}
void CPU::opcode_1c() {}
void CPU::opcode_1d() {}
void CPU::opcode_1e() {}
void CPU::opcode_1f() {}

void CPU::opcode_20() {}
void CPU::opcode_21() {}
void CPU::opcode_22() {}
void CPU::opcode_23() {}
void CPU::opcode_24() {}
void CPU::opcode_25() {}
void CPU::opcode_26() {}
void CPU::opcode_27() {}
void CPU::opcode_28() {}
void CPU::opcode_29() {}
void CPU::opcode_2a() {}
void CPU::opcode_2b() {}
void CPU::opcode_2c() {}
void CPU::opcode_2d() {}
void CPU::opcode_2e() {}
void CPU::opcode_2f() {}

void CPU::opcode_30() {}
void CPU::opcode_31() {}
void CPU::opcode_32() {}
void CPU::opcode_33() {}
void CPU::opcode_34() {}
void CPU::opcode_35() {}
void CPU::opcode_36() {}
void CPU::opcode_37() {}
void CPU::opcode_38() {}
void CPU::opcode_39() {}
void CPU::opcode_3a() {}
void CPU::opcode_3b() {}
void CPU::opcode_3c() {}
void CPU::opcode_3d() {}
void CPU::opcode_3e() {}
void CPU::opcode_3f() {}

void CPU::opcode_40() {}
void CPU::opcode_41() {}
void CPU::opcode_42() {}
void CPU::opcode_43() {}
void CPU::opcode_44() {}
void CPU::opcode_45() {}
void CPU::opcode_46() {}
void CPU::opcode_47() {}
void CPU::opcode_48() {}
void CPU::opcode_49() {}
void CPU::opcode_4a() {}
void CPU::opcode_4b() {}
void CPU::opcode_4c() {}
void CPU::opcode_4d() {}
void CPU::opcode_4e() {}
void CPU::opcode_4f() {}

void CPU::opcode_50() {}
void CPU::opcode_51() {}
void CPU::opcode_52() {}
void CPU::opcode_53() {}
void CPU::opcode_54() {}
void CPU::opcode_55() {}
void CPU::opcode_56() {}
void CPU::opcode_57() {}
void CPU::opcode_58() {}
void CPU::opcode_59() {}
void CPU::opcode_5a() {}
void CPU::opcode_5b() {}
void CPU::opcode_5c() {}
void CPU::opcode_5d() {}
void CPU::opcode_5e() {}
void CPU::opcode_5f() {}

void CPU::opcode_60() {}
void CPU::opcode_61() {}
void CPU::opcode_62() {}
void CPU::opcode_63() {}
void CPU::opcode_64() {}
void CPU::opcode_65() {}
void CPU::opcode_66() {}
void CPU::opcode_67() {}
void CPU::opcode_68() {}
void CPU::opcode_69() {}
void CPU::opcode_6a() {}
void CPU::opcode_6b() {}
void CPU::opcode_6c() {}
void CPU::opcode_6d() {}
void CPU::opcode_6e() {}
void CPU::opcode_6f() {}

void CPU::opcode_70() {}
void CPU::opcode_71() {}
void CPU::opcode_72() {}
void CPU::opcode_73() {}
void CPU::opcode_74() {}
void CPU::opcode_75() {}
void CPU::opcode_76() {}
void CPU::opcode_77() {}
void CPU::opcode_78() {}
void CPU::opcode_79() {}
void CPU::opcode_7a() {}
void CPU::opcode_7b() {}
void CPU::opcode_7c() {}
void CPU::opcode_7d() {}
void CPU::opcode_7e() {}
void CPU::opcode_7f() {}

void CPU::opcode_80() {}
void CPU::opcode_81() {}
void CPU::opcode_82() {}
void CPU::opcode_83() {}
void CPU::opcode_84() {}
void CPU::opcode_85() {}
void CPU::opcode_86() {}
void CPU::opcode_87() {}
void CPU::opcode_88() {}
void CPU::opcode_89() {}
void CPU::opcode_8a() {}
void CPU::opcode_8b() {}
void CPU::opcode_8c() {}
void CPU::opcode_8d() {}
void CPU::opcode_8e() {}
void CPU::opcode_8f() {}

void CPU::opcode_90() {}
void CPU::opcode_91() {}
void CPU::opcode_92() {}
void CPU::opcode_93() {}
void CPU::opcode_94() {}
void CPU::opcode_95() {}
void CPU::opcode_96() {}
void CPU::opcode_97() {}
void CPU::opcode_98() {}
void CPU::opcode_99() {}
void CPU::opcode_9a() {}
void CPU::opcode_9b() {}
void CPU::opcode_9c() {}
void CPU::opcode_9d() {}
void CPU::opcode_9e() {}
void CPU::opcode_9f() {}

void CPU::opcode_a0() {}
void CPU::opcode_a1() {}
void CPU::opcode_a2() {}
void CPU::opcode_a3() {}
void CPU::opcode_a4() {}
void CPU::opcode_a5() {}
void CPU::opcode_a6() {}
void CPU::opcode_a7() {}
void CPU::opcode_a8() {}
void CPU::opcode_a9() {}
void CPU::opcode_aa() {}
void CPU::opcode_ab() {}
void CPU::opcode_ac() {}
void CPU::opcode_ad() {}
void CPU::opcode_ae() {}
void CPU::opcode_af() {}

void CPU::opcode_b0() {}
void CPU::opcode_b1() {}
void CPU::opcode_b2() {}
void CPU::opcode_b3() {}
void CPU::opcode_b4() {}
void CPU::opcode_b5() {}
void CPU::opcode_b6() {}
void CPU::opcode_b7() {}
void CPU::opcode_b8() {}
void CPU::opcode_b9() {}
void CPU::opcode_ba() {}
void CPU::opcode_bb() {}
void CPU::opcode_bc() {}
void CPU::opcode_bd() {}
void CPU::opcode_be() {}
void CPU::opcode_bf() {}

void CPU::opcode_c0() {}
void CPU::opcode_c1() {}
void CPU::opcode_c2() {}
void CPU::opcode_c3() {}
void CPU::opcode_c4() {}
void CPU::opcode_c5() {}
void CPU::opcode_c6() {}
void CPU::opcode_c7() {}
void CPU::opcode_c8() {}
void CPU::opcode_c9() {}
void CPU::opcode_ca() {}
void CPU::opcode_cb() {}
void CPU::opcode_cc() {}
void CPU::opcode_cd() {}
void CPU::opcode_ce() {}
void CPU::opcode_cf() {}

void CPU::opcode_d0() {}
void CPU::opcode_d1() {}
void CPU::opcode_d2() {}
void CPU::opcode_d3() {}
void CPU::opcode_d4() {}
void CPU::opcode_d5() {}
void CPU::opcode_d6() {}
void CPU::opcode_d7() {}
void CPU::opcode_d8() {}
void CPU::opcode_d9() {}
void CPU::opcode_da() {}
void CPU::opcode_db() {}
void CPU::opcode_dc() {}
void CPU::opcode_dd() {}
void CPU::opcode_de() {}
void CPU::opcode_df() {}

void CPU::opcode_e0() {}
void CPU::opcode_e1() {}
void CPU::opcode_e2() {}
void CPU::opcode_e3() {}
void CPU::opcode_e4() {}
void CPU::opcode_e5() {}
void CPU::opcode_e6() {}
void CPU::opcode_e7() {}
void CPU::opcode_e8() {}
void CPU::opcode_e9() {}
void CPU::opcode_ea() {}
void CPU::opcode_eb() {}
void CPU::opcode_ec() {}
void CPU::opcode_ed() {}
void CPU::opcode_ee() {}
void CPU::opcode_ef() {}

void CPU::opcode_f0() {}
void CPU::opcode_f1() {}
void CPU::opcode_f2() {}
void CPU::opcode_f3() {}
void CPU::opcode_f4() {}
void CPU::opcode_f5() {}
void CPU::opcode_f6() {}
void CPU::opcode_f7() {}
void CPU::opcode_f8() {}
void CPU::opcode_f9() {}
void CPU::opcode_fa() {}
void CPU::opcode_fb() {}
void CPU::opcode_fc() {}
void CPU::opcode_fd() {}
void CPU::opcode_fe() {}
void CPU::opcode_ff() {}



// Implementing functions from opcode_cb_00 to opcode_cb_ff in CPU namespace
void CPU::opcode_cb_00() {}
void CPU::opcode_cb_01() {}
void CPU::opcode_cb_02() {}
void CPU::opcode_cb_03() {}
void CPU::opcode_cb_04() {}
void CPU::opcode_cb_05() {}
void CPU::opcode_cb_06() {}
void CPU::opcode_cb_07() {}
void CPU::opcode_cb_08() {}
void CPU::opcode_cb_09() {}
void CPU::opcode_cb_0a() {}
void CPU::opcode_cb_0b() {}
void CPU::opcode_cb_0c() {}
void CPU::opcode_cb_0d() {}
void CPU::opcode_cb_0e() {}
void CPU::opcode_cb_0f() {}

void CPU::opcode_cb_10() {}
void CPU::opcode_cb_11() {}
void CPU::opcode_cb_12() {}
void CPU::opcode_cb_13() {}
void CPU::opcode_cb_14() {}
void CPU::opcode_cb_15() {}
void CPU::opcode_cb_16() {}
void CPU::opcode_cb_17() {}
void CPU::opcode_cb_18() {}
void CPU::opcode_cb_19() {}
void CPU::opcode_cb_1a() {}
void CPU::opcode_cb_1b() {}
void CPU::opcode_cb_1c() {}
void CPU::opcode_cb_1d() {}
void CPU::opcode_cb_1e() {}
void CPU::opcode_cb_1f() {}

void CPU::opcode_cb_20() {}
void CPU::opcode_cb_21() {}
void CPU::opcode_cb_22() {}
void CPU::opcode_cb_23() {}
void CPU::opcode_cb_24() {}
void CPU::opcode_cb_25() {}
void CPU::opcode_cb_26() {}
void CPU::opcode_cb_27() {}
void CPU::opcode_cb_28() {}
void CPU::opcode_cb_29() {}
void CPU::opcode_cb_2a() {}
void CPU::opcode_cb_2b() {}
void CPU::opcode_cb_2c() {}
void CPU::opcode_cb_2d() {}
void CPU::opcode_cb_2e() {}
void CPU::opcode_cb_2f() {}

void CPU::opcode_cb_30() {}
void CPU::opcode_cb_31() {}
void CPU::opcode_cb_32() {}
void CPU::opcode_cb_33() {}
void CPU::opcode_cb_34() {}
void CPU::opcode_cb_35() {}
void CPU::opcode_cb_36() {}
void CPU::opcode_cb_37() {}
void CPU::opcode_cb_38() {}
void CPU::opcode_cb_39() {}
void CPU::opcode_cb_3a() {}
void CPU::opcode_cb_3b() {}
void CPU::opcode_cb_3c() {}
void CPU::opcode_cb_3d() {}
void CPU::opcode_cb_3e() {}
void CPU::opcode_cb_3f() {}

void CPU::opcode_cb_40() {}
void CPU::opcode_cb_41() {}
void CPU::opcode_cb_42() {}
void CPU::opcode_cb_43() {}
void CPU::opcode_cb_44() {}
void CPU::opcode_cb_45() {}
void CPU::opcode_cb_46() {}
void CPU::opcode_cb_47() {}
void CPU::opcode_cb_48() {}
void CPU::opcode_cb_49() {}
void CPU::opcode_cb_4a() {}
void CPU::opcode_cb_4b() {}
void CPU::opcode_cb_4c() {}
void CPU::opcode_cb_4d() {}
void CPU::opcode_cb_4e() {}
void CPU::opcode_cb_4f() {}

void CPU::opcode_cb_50() {}
void CPU::opcode_cb_51() {}
void CPU::opcode_cb_52() {}
void CPU::opcode_cb_53() {}
void CPU::opcode_cb_54() {}
void CPU::opcode_cb_55() {}
void CPU::opcode_cb_56() {}
void CPU::opcode_cb_57() {}
void CPU::opcode_cb_58() {}
void CPU::opcode_cb_59() {}
void CPU::opcode_cb_5a() {}
void CPU::opcode_cb_5b() {}
void CPU::opcode_cb_5c() {}
void CPU::opcode_cb_5d() {}
void CPU::opcode_cb_5e() {}
void CPU::opcode_cb_5f() {}

void CPU::opcode_cb_60() {}
void CPU::opcode_cb_61() {}
void CPU::opcode_cb_62() {}
void CPU::opcode_cb_63() {}
void CPU::opcode_cb_64() {}
void CPU::opcode_cb_65() {}
void CPU::opcode_cb_66() {}
void CPU::opcode_cb_67() {}
void CPU::opcode_cb_68() {}
void CPU::opcode_cb_69() {}
void CPU::opcode_cb_6a() {}
void CPU::opcode_cb_6b() {}
void CPU::opcode_cb_6c() {}
void CPU::opcode_cb_6d() {}
void CPU::opcode_cb_6e() {}
void CPU::opcode_cb_6f() {}

void CPU::opcode_cb_70() {}
void CPU::opcode_cb_71() {}
void CPU::opcode_cb_72() {}
void CPU::opcode_cb_73() {}
void CPU::opcode_cb_74() {}
void CPU::opcode_cb_75() {}
void CPU::opcode_cb_76() {}
void CPU::opcode_cb_77() {}
void CPU::opcode_cb_78() {}
void CPU::opcode_cb_79() {}
void CPU::opcode_cb_7a() {}
void CPU::opcode_cb_7b() {}
void CPU::opcode_cb_7c() {}
void CPU::opcode_cb_7d() {}
void CPU::opcode_cb_7e() {}
void CPU::opcode_cb_7f() {}

void CPU::opcode_cb_80() {}
void CPU::opcode_cb_81() {}
void CPU::opcode_cb_82() {}
void CPU::opcode_cb_83() {}
void CPU::opcode_cb_84() {}
void CPU::opcode_cb_85() {}
void CPU::opcode_cb_86() {}
void CPU::opcode_cb_87() {}
void CPU::opcode_cb_88() {}
void CPU::opcode_cb_89() {}
void CPU::opcode_cb_8a() {}
void CPU::opcode_cb_8b() {}
void CPU::opcode_cb_8c() {}
void CPU::opcode_cb_8d() {}
void CPU::opcode_cb_8e() {}
void CPU::opcode_cb_8f() {}

void CPU::opcode_cb_90() {}
void CPU::opcode_cb_91() {}
void CPU::opcode_cb_92() {}
void CPU::opcode_cb_93() {}
void CPU::opcode_cb_94() {}
void CPU::opcode_cb_95() {}
void CPU::opcode_cb_96() {}
void CPU::opcode_cb_97() {}
void CPU::opcode_cb_98() {}
void CPU::opcode_cb_99() {}
void CPU::opcode_cb_9a() {}
void CPU::opcode_cb_9b() {}
void CPU::opcode_cb_9c() {}
void CPU::opcode_cb_9d() {}
void CPU::opcode_cb_9e() {}
void CPU::opcode_cb_9f() {}

void CPU::opcode_cb_a0() {}
void CPU::opcode_cb_a1() {}
void CPU::opcode_cb_a2() {}
void CPU::opcode_cb_a3() {}
void CPU::opcode_cb_a4() {}
void CPU::opcode_cb_a5() {}
void CPU::opcode_cb_a6() {}
void CPU::opcode_cb_a7() {}
void CPU::opcode_cb_a8() {}
void CPU::opcode_cb_a9() {}
void CPU::opcode_cb_aa() {}
void CPU::opcode_cb_ab() {}
void CPU::opcode_cb_ac() {}
void CPU::opcode_cb_ad() {}
void CPU::opcode_cb_ae() {}
void CPU::opcode_cb_af() {}

void CPU::opcode_cb_b0() {}
void CPU::opcode_cb_b1() {}
void CPU::opcode_cb_b2() {}
void CPU::opcode_cb_b3() {}
void CPU::opcode_cb_b4() {}
void CPU::opcode_cb_b5() {}
void CPU::opcode_cb_b6() {}
void CPU::opcode_cb_b7() {}
void CPU::opcode_cb_b8() {}
void CPU::opcode_cb_b9() {}
void CPU::opcode_cb_ba() {}
void CPU::opcode_cb_bb() {}
void CPU::opcode_cb_bc() {}
void CPU::opcode_cb_bd() {}
void CPU::opcode_cb_be() {}
void CPU::opcode_cb_bf() {}

void CPU::opcode_cb_c0() {}
void CPU::opcode_cb_c1() {}
void CPU::opcode_cb_c2() {}
void CPU::opcode_cb_c3() {}
void CPU::opcode_cb_c4() {}
void CPU::opcode_cb_c5() {}
void CPU::opcode_cb_c6() {}
void CPU::opcode_cb_c7() {}
void CPU::opcode_cb_c8() {}
void CPU::opcode_cb_c9() {}
void CPU::opcode_cb_ca() {}
void CPU::opcode_cb_cb() {}
void CPU::opcode_cb_cc() {}
void CPU::opcode_cb_cd() {}
void CPU::opcode_cb_ce() {}
void CPU::opcode_cb_cf() {}

void CPU::opcode_cb_d0() {}
void CPU::opcode_cb_d1() {}
void CPU::opcode_cb_d2() {}
void CPU::opcode_cb_d3() {}
void CPU::opcode_cb_d4() {}
void CPU::opcode_cb_d5() {}
void CPU::opcode_cb_d6() {}
void CPU::opcode_cb_d7() {}
void CPU::opcode_cb_d8() {}
void CPU::opcode_cb_d9() {}
void CPU::opcode_cb_da() {}
void CPU::opcode_cb_db() {}
void CPU::opcode_cb_dc() {}
void CPU::opcode_cb_dd() {}
void CPU::opcode_cb_de() {}
void CPU::opcode_cb_df() {}

void CPU::opcode_cb_e0() {}
void CPU::opcode_cb_e1() {}
void CPU::opcode_cb_e2() {}
void CPU::opcode_cb_e3() {}
void CPU::opcode_cb_e4() {}
void CPU::opcode_cb_e5() {}
void CPU::opcode_cb_e6() {}
void CPU::opcode_cb_e7() {}
void CPU::opcode_cb_e8() {}
void CPU::opcode_cb_e9() {}
void CPU::opcode_cb_ea() {}
void CPU::opcode_cb_eb() {}
void CPU::opcode_cb_ec() {}
void CPU::opcode_cb_ed() {}
void CPU::opcode_cb_ee() {}
void CPU::opcode_cb_ef() {}

void CPU::opcode_cb_f0() {}
void CPU::opcode_cb_f1() {}
void CPU::opcode_cb_f2() {}
void CPU::opcode_cb_f3() {}
void CPU::opcode_cb_f4() {}
void CPU::opcode_cb_f5() {}
void CPU::opcode_cb_f6() {}
void CPU::opcode_cb_f7() {}
void CPU::opcode_cb_f8() {}
void CPU::opcode_cb_f9() {}
void CPU::opcode_cb_fa() {}
void CPU::opcode_cb_fb() {}
void CPU::opcode_cb_fc() {}
void CPU::opcode_cb_fd() {}
void CPU::opcode_cb_fe() {}
void CPU::opcode_cb_ff() {}
